# syntax=docker/dockerfile:1
FROM golang:1.17-alpine3.13 as builder
WORKDIR /go/src/ScooterServer
COPY . .
ENV GO111MODULE=on
ENV GOPROXY https://proxy.golang.org,direct
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o build/scooterserver

FROM scratch
COPY --from=builder /go/src/ProblemMicro/build/scooterserver /usr/bin/scooterserver
ENTRYPOINT [ "/usr/bin/scooterserver" ]
