// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/order_micro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID        uint64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ScooterID     uint64   `protobuf:"varint,3,opt,name=scooterID,proto3" json:"scooterID,omitempty"`
	StatusStartID uint64   `protobuf:"varint,4,opt,name=statusStartID,proto3" json:"statusStartID,omitempty"`
	StatusEndID   uint64   `protobuf:"varint,5,opt,name=statusEndID,proto3" json:"statusEndID,omitempty"`
	Distance      float64  `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`
	Amount        []uint64 `protobuf:"varint,7,rep,packed,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_order_micro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_micro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_micro_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Order) GetScooterID() uint64 {
	if x != nil {
		return x.ScooterID
	}
	return 0
}

func (x *Order) GetStatusStartID() uint64 {
	if x != nil {
		return x.StatusStartID
	}
	return 0
}

func (x *Order) GetStatusEndID() uint64 {
	if x != nil {
		return x.StatusEndID
	}
	return 0
}

func (x *Order) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Order) GetAmount() []uint64 {
	if x != nil {
		return x.Amount
	}
	return nil
}

type TripInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ScooterID     uint64 `protobuf:"varint,2,opt,name=scooterID,proto3" json:"scooterID,omitempty"`
	StatusStartID uint64 `protobuf:"varint,3,opt,name=statusStartID,proto3" json:"statusStartID,omitempty"`
	StatusEndID   uint64 `protobuf:"varint,4,opt,name=statusEndID,proto3" json:"statusEndID,omitempty"`
}

func (x *TripInfo) Reset() {
	*x = TripInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_order_micro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripInfo) ProtoMessage() {}

func (x *TripInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_micro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripInfo.ProtoReflect.Descriptor instead.
func (*TripInfo) Descriptor() ([]byte, []int) {
	return file_proto_order_micro_proto_rawDescGZIP(), []int{1}
}

func (x *TripInfo) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TripInfo) GetScooterID() uint64 {
	if x != nil {
		return x.ScooterID
	}
	return 0
}

func (x *TripInfo) GetStatusStartID() uint64 {
	if x != nil {
		return x.StatusStartID
	}
	return 0
}

func (x *TripInfo) GetStatusEndID() uint64 {
	if x != nil {
		return x.StatusEndID
	}
	return 0
}

var File_proto_order_micro_proto protoreflect.FileDescriptor

var file_proto_order_micro_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc9, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x45, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x64, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a,
	0x08, 0x54, 0x72, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45,
	0x6e, 0x64, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x45, 0x6e, 0x64, 0x49, 0x44, 0x32, 0x3e, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x72, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_order_micro_proto_rawDescOnce sync.Once
	file_proto_order_micro_proto_rawDescData = file_proto_order_micro_proto_rawDesc
)

func file_proto_order_micro_proto_rawDescGZIP() []byte {
	file_proto_order_micro_proto_rawDescOnce.Do(func() {
		file_proto_order_micro_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_order_micro_proto_rawDescData)
	})
	return file_proto_order_micro_proto_rawDescData
}

var file_proto_order_micro_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_order_micro_proto_goTypes = []interface{}{
	(*Order)(nil),    // 0: proto.Order
	(*TripInfo)(nil), // 1: proto.TripInfo
}
var file_proto_order_micro_proto_depIdxs = []int32{
	1, // 0: proto.OrderService.CreateOrder:input_type -> proto.TripInfo
	0, // 1: proto.OrderService.CreateOrder:output_type -> proto.Order
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_micro_proto_init() }
func file_proto_order_micro_proto_init() {
	if File_proto_order_micro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_order_micro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_order_micro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_order_micro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_micro_proto_goTypes,
		DependencyIndexes: file_proto_order_micro_proto_depIdxs,
		MessageInfos:      file_proto_order_micro_proto_msgTypes,
	}.Build()
	File_proto_order_micro_proto = out.File
	file_proto_order_micro_proto_rawDesc = nil
	file_proto_order_micro_proto_goTypes = nil
	file_proto_order_micro_proto_depIdxs = nil
}
